[tool.poetry]
name = "automating-the-boring-stuff"
version = "0.1.0"
description = ""
authors = ["giftcup"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
black = "^24.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
